lang: en-UK
title: Ioannis Markakis
position: PhD Candidate
affiliation: University of Cambridge
affiliation_link: https://www.cst.cam.ac.uk/
email: ioannis.markakis@cl.cam.ac.uk
description: Ioannis Markakis is a PhD Candidate in Computer Science at the University of Cambridge.
keywords: ioannis markakis, markakis ioannis, computads, higher category theory
baseurl: "" 
url: "https://jmarkakis.github.io" 
canonical: "https://jmarkakis.github.io" 
github_username:  jmarkakis
google_scholar: Uou1WBwAAAAJ&hl=en
cv_link: assets/pdf/curriculum_vitae.pdf
# linkedin: ioannis-markakis-a3636b253
orcid: 0000-0001-7553-9009
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon.png
remote_theme: yaoyao-liu/minimal-light
google_analytics: G-T0FC7R60JK
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/